#!/bin/sh
# generate-dnsmasq-config.sh
# 根據 /etc/config/dhcp 與 OpenWrt uci 設定，產生 /var/etc/dnsmasq.default.conf

set -e

CFG_NAME="default"
CONFIGFILE="/var/etc/dnsmasq.${CFG_NAME}.conf"
HOSTFILE="/tmp/hosts/dhcp.${CFG_NAME}"
HOSTFILE_DIR="$(dirname "$HOSTFILE")"
BASECONFIGFILE="/var/etc/dnsmasq.conf"

mkdir -p /var/run/dnsmasq
mkdir -p /var/etc
mkdir -p "$HOSTFILE_DIR"

# 引入必要函式庫
. /lib/functions.sh
. /lib/functions/network.sh

# 清除暫存
CONFIGFILE_TMP="$CONFIGFILE.$$"
HOSTFILE_TMP="$HOSTFILE.$$"
echo "# auto-generated by generate-dnsmasq-config.sh" > "$CONFIGFILE_TMP"
echo "# auto-generated by generate-dnsmasq-config.sh" > "$HOSTFILE_TMP"

# 建立 xappend 功能
xappend() {
	echo "$1" >> "$CONFIGFILE_TMP"
}

# 匯入 DHCP 設定並轉換
config_load dhcp

append_interface() {
	local ifname
	network_get_device ifname "$1" || ifname="$1"
	xappend "interface=$ifname"
}

append_server() {
	xappend "server=$1"
}

append_address() {
	xappend "address=$1"
}

config_list_foreach "$CFG_NAME" "interface" append_interface
config_list_foreach "$CFG_NAME" "server" append_server
config_list_foreach "$CFG_NAME" "address" append_address

# 常用選項
xappend "addn-hosts=$HOSTFILE"
xappend "dhcp-authoritative"
xappend "dhcp-broadcast=tag:needs-broadcast"
xappend "dhcp-leasefile=/tmp/dhcp.leases"

# 若存在額外設定則加入
[ -f /etc/dnsmasq.${CFG_NAME}.conf ] && xappend "conf-file=/etc/dnsmasq.${CFG_NAME}.conf"
[ -f /usr/share/dnsmasq/trust-anchors.conf ] && xappend "conf-file=/usr/share/dnsmasq/trust-anchors.conf"

mv "$CONFIGFILE_TMP" "$CONFIGFILE"
mv "$HOSTFILE_TMP" "$HOSTFILE"
